Renomear métodos parse para algum nome que seja mais explícito
brazilian-utils/python pull request #112
Opened 2023-06-25 10:38 UTC by antoniamaia

2023-06-25 10:44 UTC, camilamaia commented on tests/test_cnpj.py
> +        with patch("brutils.cnpj.remove_symbols") as mock_remove_symbols:
Aqui você quer verificar se o sieve foi chamado, então o mock tem que ser do sieve e nao do proprio remove_symbols.

porque no teste, vc quer testar que ao chamar o remove_symbols, o sieve será chamado.

2023-06-25 11:05 UTC, antoniamaia commented on tests/test_cnpj.py
> +        with patch("brutils.cnpj.remove_symbols") as mock_remove_symbols:
perfeito, Camila! Obrigada pela ajuda ❤️

2023-06-25 11:07 UTC, antoniamaia commented
closes #110

2023-06-26 09:07 UTC, camilamaia requested changes
Quanto ao código, tá 💯. Arrasou! 

A documentação que foi alterada é da versão 1.0.1, da versão antiga. A ideia seria a gente não mudar nada da versão anterior para não confundir quem já utiliza a biblioteca. Além disso, o método que foi renomeado foi o `parse` e não o `sieve`. Então o correto seria alterar a documentação nos READMEs (pt-br e en), mudando o `parse` para `remove_symbols`. Faz sentido?

2023-06-26 09:14 UTC, camilamaia commented
Ah, aqui também daria para deixar o título e a descrição do PR um pouco mais explícitos. Por exemplo:

Título
```Alteração do nome dos métodos `parse` para `remove_symbols` ```

Descrição
```
* Alteração de `cpf.parse` para `cpf.remove_symbols`
* Alteração de `parse_cpf` para `remove_symbols_cpf`
* Alteração de `cnpj.parse` para `cnpj.remove_symbols`
* Alteração de `parse_cnpj` para `remove_symbols_cnpj`
* Atualização da documentação

Closes #110
```

2023-06-26 22:33 UTC, antoniamaia commented
> Ah, aqui também daria para deixar o título e a descrição do PR um pouco mais explícitos. Por exemplo:
> 
> Título `` Alteração do nome dos métodos `parse` para `remove_symbols` ``
> 
> Descrição
> 
> ```
> * Alteração de `cpf.parse` para `cpf.remove_symbols`
> * Alteração de `parse_cpf` para `remove_symbols_cpf`
> * Alteração de `cnpj.parse` para `cnpj.remove_symbols`
> * Alteração de `parse_cnpj` para `remove_symbols_cnpj`
> * Atualização da documentação
> 
> Closes #110
> ```
> 
> Ah, e sempre dá para editar as informações do PR depois
> 
> ![image](https://user-images.githubusercontent.com/2728804/248744986-c308bce3-cb96-4009-998c-1474f3f475bb.png)
> 
> ![image](https://user-images.githubusercontent.com/2728804/248745049-f38ed440-b7a1-4839-a5b1-663241464cc8.png)

Obrigada, @camilamaia! Você é perfeita ❤️ estudar com você é sensacional, tudo muito claro e bem explicadinho! Acredito que agora, finally closed #110?  🙌🏼

2023-06-26 22:34 UTC, antoniamaia commented
> Obrigada, @camilamaia! Você é perfeita heart estudar com você é sensacional, tudo muito claro e bem explicadinho! Acredito que agora, finally closed #110? 🙌🏼

2023-06-27 08:49 UTC, camilamaia commented on documentation v1.0.1/ENGLISH_VERSION.md
> +>> cpf.sieve('000.111.222-33')
```suggestion
>>> cpf.sieve('000.111.222-33')
```

2023-06-27 08:51 UTC, camilamaia commented on documentation v1.0.1/ENGLISH_VERSION.md
> +>> cpf.sieve('000.111.222-33')
Mini detalhe e depois só dale 🚀

2023-06-27 09:55 UTC, camilamaia approved these changes
Mazaaaahhhh🏅

2023-06-27 09:55 UTC, merged