Feature: Validação de telefone
brazilian-utils/python pull request #150
Opened 2023-08-31 13:06 UTC by antoniamaia

2023-09-04 12:20 UTC, camilamaia requested changes

2023-09-04 12:20 UTC, camilamaia commented on README.md
> +## Phone
Talvez desse para adicionar na documentação dos telefones que o formato esperado é com o DDD (só dois números) e que sempre validará apenas números brasileiros. Talvez seria legal mostrar tb que um telefone como +55 48 9999 9999, por exemplo, ficaria '4899999999'.

O quê você acha?

2023-09-04 12:20 UTC, camilamaia commented on README.md
> +  - [is_valid_phone](#is_valid_phone)
Pequeno detalhe, mas talvez eu trocaria a ordem, colocando o `is_valid_phone` por primeiro, porque possivelmente ele vai ser o mais utilizado.

Essa foi a ordem utilizada pela versão JS:

<img width="211" alt="image" src="https://github.com/brazilian-utils/brutils-python/assets/2728804/a05acb2a-7aa8-43df-9d55-de6d491f900e">

2023-09-04 12:20 UTC, camilamaia commented on README.md
> +>>> is_valid_mobile_phone('01994029275')
Quem sabe, para manter o padrão dos outros dois exemplos, poderíamos colocar um caso em que também retornasse True.

2023-09-04 12:20 UTC, camilamaia commented on brutils/phone.py
> +            or phone_number[2] == "5"
Mini desafio: tentar trocar essas 4 linhas por 1 só, utilizando o operador `in` (membership operator): https://wiingy.com/learn/python/python-membership-and-identity-operators/

2023-09-04 12:20 UTC, camilamaia commented on tests/test_phone.py
> +from unittest.mock import patch
Arrasou demais nos testes!!! 👏👏👏👏

2023-09-04 20:28 UTC, antoniamaia commented on README.md
> +## Phone
show! pensei na mesma coisa 😍

2023-09-05 16:51 UTC, camilamaia commented on brutils/phone.py
> +        and phone_number[2] in ["2", "3", "4", "5"]
Aeeee!!! 👏👏👏

2023-09-05 17:04 UTC, camilamaia approved these changes
🤩🤩🤩🤩

2023-09-05 20:21 UTC, merged