Remover Símbolos do Número de Telefone
brazilian-utils/python pull request #188
Opened 2023-10-02 19:19 UTC by giovannism20

## Descrição
#187 

## Mudanças Propostas

## Checklist de Revisão

- [X] Os testes foram adicionados ou atualizados para refletir as mudanças (se aplicável).
- [ ] Foi adicionada uma entrada no changelog / Meu PR não necessita de uma nova entrada no changelog.
- [ ] A documentação em português foi atualizada ou criada, se necessário.
- [ ] Se feita a documentação, a atualização do arquivo em inglês. 
- [ ] Eu documentei as minhas mudanças no código, adicionando docstrings e comentários. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#8-fa%C3%A7a-as-suas-altera%C3%A7%C3%B5es)
- [ ] O código segue as diretrizes de estilo e padrões de codificação do projeto.
- [ ] Todos os testes passam. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#testes)
- [ ] O Pull Request foi testado localmente. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#7-execute-o-brutils-localmente)
- [ ] Não há conflitos de mesclagem.

## Comentários Adicionais (opcional)

## Issue Relacionada

Closes #187

2023-10-02 19:30 UTC, giovannism20 commented on documentation v1.0.1/ENGLISH_VERSION.md
> +>>> from brutils import cpf, cnpj, phone
Seria interessante colocar mais casos de exemplo para as outras funções ? Como: is_valid_landline, is_valid_mobile e is_valid ?

2023-10-02 19:31 UTC, giovannism20 commented on documentation v1.0.1/PORTUGUESE_VERSION.md
> +>>> from brutils import cpf, cnpj, phone
Seria interessante colocar mais casos de exemplo para as outras funções ? Como: is_valid_landline, is_valid_mobile e is_valid ?

2023-10-02 19:33 UTC, giovannism20 commented on CHANGELOG.md
> +## [Released]
![Screenshot from 2023-10-02 16-33-19](https://github.com/brazilian-utils/brutils-python/assets/7796661/0928b001-879e-4736-bac7-44bcdf2968fb)

2023-10-02 19:33 UTC, giovannism20 commented on brutils/phone.py
> +    cleaned_phone = phone_number.replace("(", "").replace(")", "").replace("-", "")
Caso achem interessante, posso ver formas de quebrar essa linha para caber em 80 colunas

2023-10-02 19:35 UTC, giovannism20 commented on documentation v1.0.1/PORTUGUESE_VERSION.md
Acredito que pode ser interessante remover a versão, assim fica apenas um arquivo em uma única pasta para as documentações

2023-10-02 19:35 UTC, giovannism20 commented on documentation v1.0.1/ENGLISH_VERSION.md
Same from documentation/PORTUGUESE_VERSION.md

2023-10-02 19:37 UTC, giovannism20 commented
Fiquei com algumas dúvidas e coloquei nos comentários mesmo como review, conforme forem respondendo, atualizo mais o pull request!

2023-10-03 13:25 UTC, camilamaia requested changes
Muito obrigada pela contribuição!! Deixei alguns comentários com sugestões de mudanças. Também atualizamos nossa doc para deixar mais clara as instruções para as próximas.

Valeu demais!

2023-10-03 13:25 UTC, camilamaia commented on CHANGELOG.md
> +## [Released]
A gente usa esse padrão para o Changelog: https://keepachangelog.com/pt-BR/1.0.0/. Vou sugerir ali acima como ficaria no padrão :)

2023-10-03 13:25 UTC, camilamaia commented on CHANGELOG.md
> +## [Released]
```suggestion
### Added

- Utilitário `remove_symbols_phone` [#188](https://github.com/brazilian-utils/brutils-python/pull/188)
```

2023-10-03 13:25 UTC, camilamaia commented on documentation v1.0.1/ENGLISH_VERSION.md
> +>>> from brutils import cpf, cnpj, phone
Ah, desculpe se ficou confuso, mas a documentação correta para atualizar são os arquivos README.md e README_EN.md.

Os arquivos dessa pasta são de versões descontinuadas da biblioteca. Ou seja, não devem ser atualizados. Já mudamos o nome para deixar mais claro e evitar que isso aconteça de novo.

2023-10-03 13:25 UTC, camilamaia commented on tests/test_phone.py
> +    def test_remove_symbols_phone(self):
👏👏👏

2023-10-03 13:32 UTC, camilamaia commented on brutils/phone.py
> +    cleaned_phone = phone_number.replace("(", "").replace(")", "").replace("-", "")
Boa, usou o make format e já ajeitou tudo! Valeu!!

2023-10-03 15:30 UTC, giovannism20 commented
@camilamaia Atualizei os locais corretos das documentações agora e resolvi os conflitos. Se tiver mais algum ponto, só pontuar que modifico por aqui ;)

2023-10-04 07:44 UTC, camilamaia commented on README_EN.md
> +Remove symbols from phone number. ***Exemplo: +55 (21) 2569-6969 ficaria '552125696969'.***
```suggestion
Remove symbols from phone number. ***Example: +55 (21) 2569-6969 will return '552125696969'.***
```

2023-10-04 07:44 UTC, camilamaia commented on README_EN.md
> +>>> remove_symbols_phone('+55 (21) 2569-6969')
Pelo o quê eu entendi da tua implementação, ela não estaria tirando o `+` nem o ` ` (espaço), certo? Então aqui o resultado seria `+55 21 25696969` ao invés de `552125696969` se entendi certo,

Pensando aqui, acho que seria legal tirar esses dois símbolos também. @antoniamaia o quê você acha? Daí na issue de retirar o código do país, teria que passar a string sem símbolo nenhum.

2023-10-04 07:45 UTC, camilamaia commented
Valeu @giovannism20 ! Muito obrigada. Fiquei com uma dúvida só sobre quais símbolos remover, deixei ali comentado no código :) No mais, tá show!!

2023-10-04 09:30 UTC, giovannism20 commented on README_EN.md
> +>>> remove_symbols_phone('+55 (21) 2569-6969')
Atualizei a implementação e adicionei mais casos de teste :)

2023-10-04 09:39 UTC, giovannism20 commented on tests/test_phone.py
> +            remove_symbols_phone("(21) 99402-9275!"), "21994029275!"
Acham que faria sentido removermos ainda outros símbolos e realmente deixar apenas números ?
cc: @camilamaia @antoniamaia

2023-10-04 12:08 UTC, antoniamaia commented on README_EN.md
> +>>> remove_symbols_phone('+55 (21) 2569-6969')
@camilamaia Sim!! faz todo sentido

2023-10-04 12:10 UTC, antoniamaia commented on tests/test_phone.py
> +            remove_symbols_phone("(21) 99402-9275!"), "21994029275!"
@giovannism20 o padrão que estamos seguindo para os outros utilitários é de remover apenas os símbolos de cada contexto.. até poderia fazer sentido, mas como estamos seguindo este padrão poderia causar confusão para quem já utiliza a biblioteca.

2023-10-04 12:17 UTC, camilamaia approved these changes
Aeee, valeu demais, agora tá 10/10!

2023-10-04 12:19 UTC, antoniamaia approved these changes

2023-10-04 12:21 UTC, merged