feat: add is_valid_pis
brazilian-utils/python pull request #216
Opened 2023-10-04 18:11 UTC by kaioduarte

## Descrição
Adiciona suporte à validação de números PIS/PASEP.

## Mudanças Propostas

Implementação das funções de validação de números PIS/PASEP, com funções concisas que darão suporte à implementação de novas funcionalidades como a geração de números PIS aleatórios.

## Checklist de Revisão

- [x] Eu li o [Contributing.md](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md)
- [x] Os testes foram adicionados ou atualizados para refletir as mudanças (se aplicável).
- [x] Foi adicionada uma entrada no changelog / Meu PR não necessita de uma nova entrada no changelog.
- [] A [documentação](https://github.com/brazilian-utils/brutils-python/blob/main/README.md) em português foi atualizada ou criada, se necessário.
- [] Se feita a documentação, a atualização do [arquivo em inglês](https://github.com/brazilian-utils/brutils-python/blob/main/README_EN.md). 
- [x] Eu documentei as minhas mudanças no código, adicionando docstrings e comentários. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#8-fa%C3%A7a-as-suas-altera%C3%A7%C3%B5es)
- [x] O código segue as diretrizes de estilo e padrões de codificação do projeto.
- [x] Todos os testes passam. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#testes)
- [x] O Pull Request foi testado localmente. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#7-execute-o-brutils-localmente)
- [x] Não há conflitos de mesclagem.

## Comentários Adicionais (opcional)

- Adicionei type hints nas minhas funções pelo hábito de trabalhar com TypeScript :)

## Issue Relacionada

Closes #203

2023-10-04 18:35 UTC, antoniamaia requested changes
@kaioduarte demais! Obrigada pela sua contribuição.. a única coisa que faltou foi documentar a feature nos arquivos `README.md` e `README_EN.md` 😅

2023-10-04 18:43 UTC, kaioduarte commented
Oops! Obrigado por apontar, já corrigi.

2023-10-05 18:21 UTC, antoniamaia approved these changes
Perfeito, @kaioduarte.. muito obrigada pela tua contribuição!! 🎉

2023-10-05 18:29 UTC, antoniamaia approved these changes
@kaioduarte apenas ajustando o merge :)

2023-10-05 18:29 UTC, antoniamaia commented on brutils/__init__.py
> +    is_valid_old_format as is_valid_license_plate_old_format,
```suggestion
  
```

2023-10-05 18:29 UTC, antoniamaia commented on brutils/__init__.py
```suggestion
from brutils.license_plate import is_valid_license_plate_old_format
```

2023-10-05 19:04 UTC, merged