209
brazilian-utils/python pull request #222
Opened 2023-10-04 23:19 UTC by pontes-guilherme

## Descrição
Adicionada funcão para remover os símbolos de uma String que contém um número de um Processo Jurídico.

## Mudanças Propostas

- Adicionado arquivo legal_process.py que contém a função descrita.
- Adicionada importação da função no arquivo __init__.
- Adicionados testes

## Checklist de Revisão

- [:heavy_check_mark:] Eu li o [Contributing.md](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md)
- [:heavy_check_mark:] Os testes foram adicionados ou atualizados para refletir as mudanças (se aplicável).
- [:heavy_check_mark:] Foi adicionada uma entrada no changelog / Meu PR não necessita de uma nova entrada no changelog.
- [:heavy_check_mark:] A [documentação](https://github.com/brazilian-utils/brutils-python/blob/main/README.md) em português foi atualizada ou criada, se necessário.
- [:heavy_check_mark:] Se feita a documentação, a atualização do [arquivo em inglês](https://github.com/brazilian-utils/brutils-python/blob/main/README_EN.md). 
- [:heavy_check_mark:] Eu documentei as minhas mudanças no código, adicionando docstrings e comentários. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#8-fa%C3%A7a-as-suas-altera%C3%A7%C3%B5es)
- [:heavy_check_mark:] O código segue as diretrizes de estilo e padrões de codificação do projeto.
- [:heavy_check_mark:] Todos os testes passam. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#testes)
- [:heavy_check_mark:] O Pull Request foi testado localmente. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#7-execute-o-brutils-localmente)
- [:heavy_check_mark:] Não há conflitos de mesclagem.

## Issue Relacionada

Closes #209

2023-10-05 20:18 UTC, antoniamaia approved these changes
boa, @pontes-guilherme.. obrigada pela contribuição!! Depois que aprovei, percebi que tinha uma pequena sugestão a fazer :)

2023-10-05 20:23 UTC, antoniamaia requested changes

2023-10-05 20:23 UTC, antoniamaia commented on README.md
> +- [Utilitários](#utilitários)
```suggestion

```
poucas linhas acima temos os mesmos links, esta aqui seria apenas uma seção para os links de utilitários :)

2023-10-05 20:23 UTC, antoniamaia commented on README.md
> +- [Contribuindo com o Código do Projeto](#contribuindo-com-o-código-do-projeto)
```suggestion

```

2023-10-06 02:15 UTC, pontes-guilherme commented
Oi, @antoniamaia. Gerei os commits de ajuste diretamente das suas sugestões. Será que isso já resolve?
Existe alguma gerção automática desses links nos readme? Não me recordo de fazer essas alterações. Apenas adicionei uma descrição breve da função após a seção de e-mail :thinking:

2023-10-06 14:22 UTC, antoniamaia approved these changes

2023-10-06 14:22 UTC, antoniamaia commented on README_EN.md
> +- [Utilities](#utilities)
```suggestion

```

2023-10-06 14:22 UTC, antoniamaia commented on README_EN.md
> +- [Code Contribution](#code-contribution)
```suggestion

```

2023-10-06 15:21 UTC, camilamaia commented on brutils/__init__.py
> +)
```suggestion
)

```

2023-10-06 15:22 UTC, camilamaia approved these changes

2023-10-06 15:24 UTC, merged