feat: add remove_symbols_license_plate
brazilian-utils/python pull request #223
Opened 2023-10-05 00:46 UTC by pontes-guilherme

## Descrição
Adicionada funcão para remover os símbolos de uma String que contém um número de uma Placa de carro.

## Mudanças Propostas

- Adicionado arquivo license_plate.py que contém a função descrita.
- Adicionada importação da função no arquivo __init__.
- Adicionados testes

## Checklist de Revisão

- [:heavy_check_mark:] Eu li o [Contributing.md](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md)
- [:heavy_check_mark:] Os testes foram adicionados ou atualizados para refletir as mudanças (se aplicável).
- [:heavy_check_mark:] Foi adicionada uma entrada no changelog / Meu PR não necessita de uma nova entrada no changelog.
- [:heavy_check_mark:] A [documentação](https://github.com/brazilian-utils/brutils-python/blob/main/README.md) em português foi atualizada ou criada, se necessário.
- [:heavy_check_mark:] Se feita a documentação, a atualização do [arquivo em inglês](https://github.com/brazilian-utils/brutils-python/blob/main/README_EN.md). 
- [:heavy_check_mark:] Eu documentei as minhas mudanças no código, adicionando docstrings e comentários. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#8-fa%C3%A7a-as-suas-altera%C3%A7%C3%B5es)
- [:heavy_check_mark:] O código segue as diretrizes de estilo e padrões de codificação do projeto.
- [:heavy_check_mark:] Todos os testes passam. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#testes)
- [:heavy_check_mark:] O Pull Request foi testado localmente. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#7-execute-o-brutils-localmente)
- [:heavy_check_mark:] Não há conflitos de mesclagem.

## Issue Relacionada

Closes #182

2023-10-06 12:44 UTC, antoniamaia requested changes
Boa, @pontes-guilherme, só ajustar mesmo aquele pequeno detalhe :)

2023-10-06 12:44 UTC, antoniamaia commented on README.md
> +- [Utilitários](#utilitários)
```suggestion
```

2023-10-06 12:44 UTC, antoniamaia commented on README.md
> +- [Contribuindo com o Código do Projeto](#contribuindo-com-o-código-do-projeto)
```suggestion
```

2023-10-06 12:44 UTC, antoniamaia commented on README_EN.md
> +- [Utilities](#utilities)
```suggestion
```

2023-10-06 12:44 UTC, antoniamaia commented on README_EN.md
> +- [Code Contribution](#code-contribution)
```suggestion
```

2023-10-08 03:41 UTC, pontes-guilherme commented
Oi, @antoniamaia. Ajustei as sugestões nos arquivos readme; também aproveitei e dei merge da versão mais recente da branch pra essa :)

Notei que a seção de processo jurídico dos arquivos readme tá duplicada. Acho que ocorreu em algum outro merge. Como não estava relacionado com esse PR, não ajustei. O que é mais correto nesse caso? Abrir uma nova issue, reabrir alguma de processo jurídico, ou fazer a correção imediatamente nessa branch mesmo?

2023-10-09 12:33 UTC, camilamaia approved these changes
🌟

2023-10-09 12:33 UTC, camilamaia commented on README.md
> -- [Processo Jurídico](#processo-juridico)
Opa, bem observado! Valeu por ajeitar essa parte também 🙂

2023-10-09 12:33 UTC, antoniamaia approved these changes

2023-10-09 12:34 UTC, merged