format pis #206
brazilian-utils/python pull request #224
Opened 2023-10-05 01:06 UTC by patricia-salles

## Descrição

Dada uma String correspondente a um número de PIS válido, retornar uma String correspondendo a este número formatada com pontos e traço.

NNN.NNNNN.NN-D

## Mudanças Propostas
Desenvolvimento das funções de validação e formatação do PIS.

## Checklist de Revisão

- [x] Eu li o [Contributing.md](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md)
- [x] Os testes foram adicionados ou atualizados para refletir as mudanças (se aplicável).
- [x] Foi adicionada uma entrada no changelog / Meu PR não necessita de uma nova entrada no changelog.
- [] A [documentação](https://github.com/brazilian-utils/brutils-python/blob/main/README.md) em português foi atualizada ou criada, se necessário.
- [] Se feita a documentação, a atualização do [arquivo em inglês](https://github.com/brazilian-utils/brutils-python/blob/main/README_EN.md). 
- [x] Eu documentei as minhas mudanças no código, adicionando docstrings e comentários. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#8-fa%C3%A7a-as-suas-altera%C3%A7%C3%B5es)
- [x] O código segue as diretrizes de estilo e padrões de codificação do projeto.
- x[] Todos os testes passam. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#testes)
- [x] O Pull Request foi testado localmente. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#7-execute-o-brutils-localmente)
- [x] Não há conflitos de mesclagem.

2023-10-06 14:09 UTC, antoniamaia requested changes
@patricia-salles além destas sugestões, faltou fazer a documentação deste novo utilitário nos arquivos `README.md` e `README_EN.md`, acredito que com estas alterações os testes irão passar :) Caso precises de alguma ajuda, só chamar ❤️

2023-10-06 14:09 UTC, antoniamaia commented on brutils/formatpis.py
> +    return "{}.{}.{}-{}".format(pis[:3], pis[3:8], pis[8:10], pis[10:11])
```suggestion
def format_pis(pis):  # type: (str) -> str
    """
    Format an adequately formatted numbers-only PIS string,
    Returns a PIS formatted with standard visual aid symbols.
    Returns None if PIS is invalid.
    """

    if not is_valid(pis):
        return None

    return "{}.{}.{}-{}".format(pis[:3], pis[3:8], pis[8:10], pis[10:11])
```
@patricia-salles a função está correta, a não ser por uma coisa:
1 - ela deve seguir o padrão dos outros utilitários, e estar no arquivo chamado `pis.py` - que é onde estão todas as outras funções deste assunto.. o mesmo acontece com os testes: todos os testes dos utilitários de PIS ficam em `test_pis.py`

2023-10-06 14:09 UTC, antoniamaia commented on tests/test_format_pis.py
> +from brutils.formatpis import validate, is_valid, format_pis, _checksum
```suggestion
from brutils.pis import validate, is_valid, format_pis, _checksum
```

2023-10-06 14:09 UTC, antoniamaia commented on tests/test_format_pis.py
> +from brutils.formatpis import validate, is_valid, format_pis, _checksum
```suggestion
from brutils.pis import validate, is_valid, format_pis, _checksum
```

2023-10-06 14:09 UTC, antoniamaia commented on tests/test_format_pis.py
> +class TestFORMATPIS(TestCase):
```suggestion
class TestPIS(TestCase):
```

2023-10-06 14:09 UTC, antoniamaia commented on tests/test_format_pis.py
> +            self.assertIsNone(format_pis("14372195539"))
```suggestion
    def test_format_pis(self):
        with patch("brutils.pis.is_valid", return_value=True) as mock_is_valid:
            # When PIS is_valid, returns formatted PIS
            self.assertEqual(format_pis("14372195539"), "143.72195.53-9")

        # Checks if function is_valid_pis is called
        mock_is_valid.assert_called_once_with("14372195539")

        with patch("brutils.pis.is_valid", return_value=False) as mock_is_valid:
            # When PIS isn't valid, returns None
            self.assertIsNone(format_pis("14372195539")) 
```

2023-10-06 22:07 UTC, patricia-salles commented on brutils/formatpis.py
> +    return "{}.{}.{}-{}".format(pis[:3], pis[3:8], pis[8:10], pis[10:11])
Oi @antoniamaia, realizei as alterações que você comentou e a documentação no README.

2023-10-09 12:26 UTC, camilamaia commented
@patricia-salles agora tá tudo redondo no PR, só falta formatar o código para passar no checagem de lint.

Para isso, basta executar `make format`, fazer o commit e o push dos arquivos modificados. Qualquer dificuldade é só dar um toque.

2023-10-09 13:43 UTC, camilamaia reviewed
Arrumando os erros que criei no merge

2023-10-09 13:43 UTC, camilamaia commented on tests/test_pis.py
> +)
```suggestion
from brutils.pis import (
    validate, 
    is_valid,
    generate,
    _checksum,
    remove_symbols,
    format_pis,
)
```

2023-10-09 13:43 UTC, camilamaia commented on tests/test_pis.py
>  from unittest import TestCase, main
```suggestion
from unittest import TestCase, main
from unittest.mock import patch
```

2023-10-09 22:52 UTC, patricia-salles commented
Oi oi @camilamaia, 
Ajustei o changelog e executei o make format. Agora passou em todas as checagens :)
Obrigada pela ajuda.

2023-10-10 14:01 UTC, camilamaia approved these changes

2023-10-10 14:01 UTC, camilamaia commented on CHANGELOG.md
> +- Utilitário `format_pis` [#206](https://github.com/brazilian-utils/brutils-python/pull/206)
Opa, aqui o número do PR tá trocado com o número da issue:

```suggestion
- Utilitário `format_pis` [#224](https://github.com/brazilian-utils/brutils-python/pull/224)
```

2023-10-10 14:15 UTC, camilamaia commented
> Oi oi @camilamaia, Ajustei o changelog e executei o make format. Agora passou em todas as checagens :) Obrigada pela ajuda.

Imagina, a gente que agradece pela contribuição e pela paciência!!

2023-10-10 17:05 UTC, antoniamaia approved these changes
Boa, @patricia-salles! Muito obrigada pela tua contribuição!! 🎉

2023-10-10 17:14 UTC, merged

2023-10-11 02:10 UTC, patricia-salles commented
@camilamaia e @antoniamaia obrigada pela ajuda e comentários. Vou dar uma olhada nas issues e vê pra pegar mais uma.