Feature: Formatando numero de telefone #189
brazilian-utils/python pull request #231
Opened 2023-10-07 03:32 UTC by jhonatacaiob

## Descrição
Criando método para formatar um numero de telefone válido para um formato legível

- Exemplo 1: Descrição da primeira alteração.
- Exemplo 2: Descrição da segunda alteração.
```py
    >>> format_phone("11994029275")
    '(11)99402-9275'
    >>> format_phone("1635014415")
    '(16)3501-4415'
    >>> format_phone("333333")
    >>> 
```
- ...-->

## Checklist de Revisão

- [x] Eu li o [Contributing.md](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md)
- [x] Os testes foram adicionados ou atualizados para refletir as mudanças (se aplicável).
- [x] Foi adicionada uma entrada no changelog / Meu PR não necessita de uma nova entrada no changelog.
- [] A [documentação](https://github.com/brazilian-utils/brutils-python/blob/main/README.md) em português foi atualizada ou criada, se necessário.
- [] Se feita a documentação, a atualização do [arquivo em inglês](https://github.com/brazilian-utils/brutils-python/blob/main/README_EN.md). 
- [x] Eu documentei as minhas mudanças no código, adicionando docstrings e comentários. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#8-fa%C3%A7a-as-suas-altera%C3%A7%C3%B5es)
- [x] O código segue as diretrizes de estilo e padrões de codificação do projeto.
- [x] Todos os testes passam. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#testes)
- [x] O Pull Request foi testado localmente. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#7-execute-o-brutils-localmente)
- [x] Não há conflitos de mesclagem.

## Issue Relacionada

https://github.com/brazilian-utils/brutils-python/issues/189

Closes #<numero_da_issue>

2023-10-09 12:42 UTC, camilamaia requested changes
O código tá 💯, valeu pela contribuição!

Só deixei duas pequenas sugestões na parte de documentação. Precisaria também adicionar as atualizações dos arquivos README.md e README_EN.md com o novo utilitário format_phone.

2023-10-09 12:42 UTC, camilamaia commented on CHANGELOG.md
> +- Utilitário `format_phone` [#189](https://github.com/brazilian-utils/brutils-python/issues/189)
Só trocando o link para ser o do PR e não para issue:

```suggestion
- Utilitário `format_phone` [#231](https://github.com/brazilian-utils/brutils-python/pull/231)
```

2023-10-09 12:42 UTC, camilamaia commented on brutils/phone.py
> +def format_phone(phone):
```suggestion
def format_phone(phone): # type: (str) -> str
```

2023-10-09 16:19 UTC, jhonatacaiob commented
> O código tá 💯, valeu pela contribuição!
> 
> Só deixei duas pequenas sugestões na parte de documentação. Precisaria também adicionar as atualizações dos arquivos README.md e README_EN.md com o novo utilitário format_phone.

Obrigado pelas sugestões @camilamaia

Apliquei as sugestões e atualizei o PR

2023-10-10 13:57 UTC, camilamaia approved these changes
@jhonatacaiob opa, valeu demais! Tá 10/10 agora!

2023-10-10 13:57 UTC, merged