Feature: Gerar um numero de celular aleatório #191
brazilian-utils/python pull request #232
Opened 2023-10-07 12:36 UTC by jhonatacaiob

## Descrição
Cria um método que gera um numero de telefone aleatório e válido

```py
>>> generate_mobile_phone()
'92942632303'
>>> generate_mobile_phone()
'17989047396'
>>> generate_mobile_phone()
'49997697725'
>>> generate_mobile_phone()
'85933479797'
>>> generate_mobile_phone()
'26979400345'
```

## Checklist de Revisão

- [x] Eu li o [Contributing.md](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md)
- [x] Os testes foram adicionados ou atualizados para refletir as mudanças (se aplicável).
- [x] Foi adicionada uma entrada no changelog / Meu PR não necessita de uma nova entrada no changelog.
- [x] A [documentação](https://github.com/brazilian-utils/brutils-python/blob/main/README.md) em português foi atualizada ou criada, se necessário.
- [x] Se feita a documentação, a atualização do [arquivo em inglês](https://github.com/brazilian-utils/brutils-python/blob/main/README_EN.md). 
- [x] Eu documentei as minhas mudanças no código, adicionando docstrings e comentários. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#8-fa%C3%A7a-as-suas-altera%C3%A7%C3%B5es)
- [x] O código segue as diretrizes de estilo e padrões de codificação do projeto.
- [x] Todos os testes passam. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#testes)
- [x] O Pull Request foi testado localmente. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#7-execute-o-brutils-localmente)
- [x] Não há conflitos de mesclagem.

## Issue Relacionada

https://github.com/brazilian-utils/brutils-python/issues/191

Closes #191

2023-10-09 13:02 UTC, camilamaia requested changes
De código tá 💯 ! Valeu pela contribuição.

Só acabou faltando atualizar os arquivos de documentação:

- CHANGELOG.md
- README.md
- README_EN.md

2023-10-09 16:43 UTC, jhonatacaiob commented
> De código tá 💯 ! Valeu pela contribuição.
> 
> Só acabou faltando atualizar os arquivos de documentação:
> 
> * CHANGELOG.md
> * README.md
> * README_EN.md


Obrigado pelas sugestões @camilamaia

Apliquei as sugestões e atualizei o PR

2023-10-10 14:53 UTC, camilamaia approved these changes

2023-10-10 14:59 UTC, camilamaia reviewed
Arrumando erros que inseri com o merge

2023-10-10 14:59 UTC, camilamaia commented on brutils/__init__.py
> +    format_license_plate,
```suggestion
     format as format_license_plate,
```

2023-10-10 14:59 UTC, camilamaia commented on brutils/phone.py
> +    ...
```suggestion

```

2023-10-10 15:02 UTC, camilamaia commented on brutils/__init__.py
> +     format as format_license_plate,
```suggestion
    format as format_license_plate,
```

2023-10-10 15:16 UTC, merged