Adicionando generate_processo_juridico #208
brazilian-utils/python pull request #246
Opened 2023-10-10 15:51 UTC by MarcelFox

## Descrição

Adicionando comando `generate_processo_jurídico` que gera números de processo jurídico válidos e aleatórios.

## Mudanças Propostas

- [x] Eu li o [Contributing.md](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md)
- [x] Os testes foram adicionados ou atualizados para refletir as mudanças (se aplicável).
- [x] Foi adicionada uma entrada no changelog / Meu PR não necessita de uma nova entrada no changelog.
- [x] A [documentação](https://github.com/brazilian-utils/brutils-python/blob/main/README.md) em português foi atualizada ou criada, se necessário.
- [x] Se feita a documentação, a atualização do [arquivo em inglês](https://github.com/brazilian-utils/brutils-python/blob/main/README_EN.md). 
- [x] Eu documentei as minhas mudanças no código, adicionando docstrings e comentários. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#8-fa%C3%A7a-as-suas-altera%C3%A7%C3%B5es)
- [x] O código segue as diretrizes de estilo e padrões de codificação do projeto.
- [x] Todos os testes passam. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#testes)
- [x] O Pull Request foi testado localmente. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#7-execute-o-brutils-localmente)
- [x] Não há conflitos de mesclagem.

## Comentários Adicionais (opcional)

## Issue Relacionada

Closes #<numero_da_issue>

2023-10-12 18:41 UTC, antoniamaia requested changes

2023-10-12 18:41 UTC, antoniamaia commented on brutils/assets/__init__.py
@MarcelFox este arquivo aqui é necessário? Se sim, pode ter faltado código aqui! :) Pelo que entendi o arquivo `legal_process_ids` contém os dados necessários, como um dicionário. Segundo estas duas fontes, não teria a necessidade deste arquivo, já que não é um pacote(ainda) de importação de módulos.. mas me corrija se estiver errada!!  https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/assets.html // https://www.shiksha.com/online-courses/articles/difference-between-module-and-package-in-python/

2023-10-12 18:41 UTC, antoniamaia commented on brutils/assets/__init__.py
Caso ele seja necessário "mais pra frente" uma ideia legal seria comentar no arquivo para que outros colaboradores também possam compreender :)

2023-10-12 21:49 UTC, MarcelFox commented on brutils/assets/__init__.py
Ele é um arquivo JSON na verdade, transformei em _dict_ pra facilitar o _import_ dele em `legal_process`.  A lógica para gerar e para também no futuro validar números de processo está nele. Se observar, temos chave e valor de forma recursiva, encontrando o _orgão_ que por sua vez tem arrays de números de seus possíveis _tribunais_ e _foros_. Mas concordo que o diretório _assets_ não é um módulo Python. Vou ajustar pra ele ser um _json_ e aí sim será só um asset dentro de assets, o que acha?

2023-10-13 14:12 UTC, MarcelFox commented on brutils/assets/__init__.py
Acabei de realizar o ajuste, quando esse PR entrar eu sigo na issue #207

2023-10-13 14:47 UTC, antoniamaia requested changes
@MarcelFox show!! muito obrigada pela contribuição.. A única coisa é que estávamos pensando aqui sobre o nome da pasta.. o que você acha de mudar de `assets` para `data`? :)

2023-10-13 14:54 UTC, antoniamaia commented on brutils/assets/__init__.py
@MarcelFox fiz uma minor suggestion ali pra ti! Mas show, muito obrigada por tuas contribuições!! :tada

2023-10-13 15:15 UTC, MarcelFox commented
> @MarcelFox show!! muito obrigada pela contribuição.. A única coisa é que estávamos pensando aqui sobre o nome da pasta.. o que você acha de mudar de `assets` para `data`? :)

feito! Valeu pelo review!

2023-10-13 15:20 UTC, antoniamaia approved these changes

2023-10-13 15:20 UTC, merged