288 - Alterando pre-commit hook para pre-push
brazilian-utils/python pull request #291
Opened 2023-11-25 21:57 UTC by MarcelFox

## Descrição

Alterar o pre-commit hook para ser um pre-push hook para facilitar o fluxo de desenvolvimento onde a checagem de código será feita apenas no push e não a cada commit.

## Mudanças Propostas

- pre-commit removido
- Adicionado modificação de diretório de githook no `make install`
- Melhorias efetuadas no poetry para o ruff check (como estava não formatava efetivamente)
- pre-push hook adicionado

## Checklist de Revisão

- [x] Eu li o [Contributing.md](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md)
- [ ] Os testes foram adicionados ou atualizados para refletir as mudanças (se aplicável).
- [x] Foi adicionada uma entrada no changelog / Meu PR não necessita de uma nova entrada no changelog.
- [ ] A [documentação](https://github.com/brazilian-utils/brutils-python/blob/main/README.md) em português foi atualizada ou criada, se necessário.
- [ ] Se feita a documentação, a atualização do [arquivo em inglês](https://github.com/brazilian-utils/brutils-python/blob/main/README_EN.md). 
- [ ] Eu documentei as minhas mudanças no código, adicionando docstrings e comentários. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#8-fa%C3%A7a-as-suas-altera%C3%A7%C3%B5es)
- [ ] O código segue as diretrizes de estilo e padrões de codificação do projeto.
- [ ] Todos os testes passam. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#testes)
- [x] O Pull Request foi testado localmente. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#7-execute-o-brutils-localmente)
- [x] Não há conflitos de mesclagem.

## Comentários Adicionais (opcional)

O que não foi marcado acima não se aplica uma vez que é uma mudança relacionada a estrutura do projeto.

## Issue Relacionada

Closes #<288>

2023-11-25 22:04 UTC, MarcelFox commented
Olha o fluxo de funcionamento, se adicionamos um commit que não vai passar no _ruff_, o push não é realizado e uma mensagem para formatar o código é informada:

![image](https://github.com/brazilian-utils/brutils-python/assets/4885041/1fa623f2-4e9b-4ae1-96a1-5d2f22f9b2bd)

2023-11-27 09:47 UTC, camilamaia requested changes
@MarcelFox valeu pela contribuição! Deixei duas sugestões apenas com pequenos detalhes.

2023-11-27 09:47 UTC, camilamaia commented on .githooks/pre-push
> +Remember to commit any changes made on the process.\n'; exit 1; fi"
```suggestion
Remember to commit any changes made on the process.\n'; exit 1; fi"

```

2023-11-27 09:47 UTC, camilamaia commented on CHANGELOG.md
> +- Adicionado pre-push hook [#288](https://github.com/brazilian-utils/brutils-python/pull/288)
Como essa modificação não afeta o usuário final, não precisamos citá-la no changelog.
```suggestion
```

2023-11-27 09:50 UTC, camilamaia commented on Makefile
> +	@poetry run ruff check . --fix
@MarcelFox Você sabe dizer qual a diferença entre `@poetry run ruff check . --fix` e `@poetry run ruff . --fix`? Eu usei o segundo e funcionou bem também.

2023-11-27 16:55 UTC, MarcelFox commented on Makefile
> +	@poetry run ruff check . --fix
O `ruff check . --fix` de fato corrige possíveis problemas encontrados, de acordo com a ducumentação:

![image](https://github.com/brazilian-utils/brutils-python/assets/4885041/8b76fd5a-75e0-4897-9e58-4e081ab7b025)

Já o `ruff . --fix` não parece ser uma opção:
![image](https://github.com/brazilian-utils/brutils-python/assets/4885041/bed1c6ed-9d8a-4798-adeb-e963aefdef1a)

O que fiquei sem entender é o `format` que pra mim não fez nada. Optei pelo `check` por que funcionou, ele corrigiu problemas e aparentemente formatou o código então optei por ele.

2023-11-28 07:04 UTC, camilamaia commented on Makefile
> +	@poetry run ruff check . --fix
Faz sentido, valeu! Também não tinha achado na doc

2023-11-28 07:04 UTC, camilamaia approved these changes

2023-11-28 07:22 UTC, merged