Tornando a função `is_valid_pis` única
brazilian-utils/python pull request #307
Opened 2023-12-19 14:01 UTC by antoniamaia

## Descrição

Haviam duas funções que faziam a mesma coisa, sem necessidade. Tornei apenas uma função `is_valid_pis`

## Mudanças Propostas

## Checklist de Revisão

- [ ] Eu li o [Contributing.md](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md)
- [ ] Os testes foram adicionados ou atualizados para refletir as mudanças (se aplicável).
- [ ] Foi adicionada uma entrada no changelog / Meu PR não necessita de uma nova entrada no changelog.
- [ ] A [documentação](https://github.com/brazilian-utils/brutils-python/blob/main/README.md) em português foi atualizada ou criada, se necessário.
- [ ] Se feita a documentação, a atualização do [arquivo em inglês](https://github.com/brazilian-utils/brutils-python/blob/main/README_EN.md). 
- [ ] Eu documentei as minhas mudanças no código, adicionando docstrings e comentários. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#8-fa%C3%A7a-as-suas-altera%C3%A7%C3%B5es)
- [ ] O código segue as diretrizes de estilo e padrões de codificação do projeto.
- [ ] Todos os testes passam. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#testes)
- [ ] O Pull Request foi testado localmente. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#7-execute-o-brutils-localmente)
- [ ] Não há conflitos de mesclagem.

## Comentários Adicionais (opcional)

## Issue Relacionada

Closes #301

2023-12-19 14:46 UTC, camilamaia commented on brutils/pis.py
> +        return False
Eu trocaria a ordem do código para garantir uma melhor leitura. Primeiro a gente trata a lógica mais genérica. Porque senão for string, por exemplo, nem precisa continuar a validar mais nada. Pode sair. 

Ai depois já sabemos que temos os pré-requisitos básicos garantidos e podemos verificar a lógica "principal", a lógica mais específica.

Outra mudança que sugeri é tirar o else. O else não precisa ser colocado já que tem um return antes no fluxo do if. Assim, quando entrar no if, nunca vai prosseguir para frente, no return já vai sair direto do método. Nunca vai passar pelo else. 

```suggestion
    if isinstance(pis, str) and len(pis) == 11 and pis.isdigit():
        return False

    return  pis[-1] == str(_checksum(pis[:-1]))
```

2023-12-19 14:47 UTC, camilamaia requested changes
Deixei uma sugestão para melhorar a leitura. Mas no mais tá tudo certo. Mandou bem demais encontrando esse método duplicado 👏

2023-12-19 15:24 UTC, antoniamaia commented
> Deixei uma sugestão para melhorar a leitura. Mas no mais tá tudo certo. Mandou bem demais encontrando esse método duplicado 👏

ajustei como tu tinhas falado, mas deu erro 😵‍💫 refatorei dese novo jeito, que foi o único que deu certo 🥲 ainda tem false 🥲

2023-12-19 16:27 UTC, camilamaia commented
> > Deixei uma sugestão para melhorar a leitura. Mas no mais tá tudo certo. Mandou bem demais encontrando esse método duplicado 👏
> 
> ajustei como tu tinhas falado, mas deu erro 😵‍💫 refatorei dese novo jeito, que foi o único que deu certo 🥲 ainda tem false 🥲

Aff, eu que errei. Esqueci do `not`. Deveria ser:

```
    if not isinstance(pis, str) or len(pis) != 11 or not pis.isdigit():
        return False
    return  pis[-1] == str(_checksum(pis[:-1]))
```

2023-12-20 07:40 UTC, camilamaia commented on brutils/pis.py
> +    return False
Tem uma dica que é, se tem um if dentro do outro if direto, sempre dá para colocar tudo em um if só com um "and"

```
    return isinstance(pis, str) and len(pis) == 11 and pis.isdigit() and pis[-1] == str(_checksum(pis[:-1]))
```

ou também dá como tinha tentando sugerir antes, mas que tinha esquecido dos not:

```
    if not isinstance(pis, str) or len(pis) != 11 or not pis.isdigit():
        return False

    return  pis[-1] == str(_checksum(pis[:-1]))
```

Como vc preferir :) A gente pode fazer um pair com isso para treinar mais as diferentes opções. Do jeito que tá agora funciona, só não estaria muito "pythônico"

2023-12-22 08:42 UTC, camilamaia approved these changes

2023-12-22 20:29 UTC, merged