Conversão de código do estado do IBGE para a sigla do Estado
brazilian-utils/python pull request #410
Opened 2024-09-13 19:25 UTC by carlos-moreno

## Descrição
Converter o código de estado do IBGE na sigla do Estado

## Mudanças Propostas
Adicionado função responsável por realizar a conversão do código de estado do IBGE na sigla do estado.

- Adicionado função de conversão `convert_code_to_uf`.
- Adicionado testes unitários.
- Importado a função no __init__.py

## Checklist de Revisão

- [X] Eu li o [Contributing.md](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md)
- [X] Os testes foram adicionados ou atualizados para refletir as mudanças (se aplicável).
- [ ] Foi adicionada uma entrada no changelog / Meu PR não necessita de uma nova entrada no changelog.
- [ ] A [documentação](https://github.com/brazilian-utils/brutils-python/blob/main/README.md) em português foi atualizada ou criada, se necessário.
- [ ] Se feita a documentação, a atualização do [arquivo em inglês](https://github.com/brazilian-utils/brutils-python/blob/main/README_EN.md). 
- [ ] Eu documentei as minhas mudanças no código, adicionando docstrings e comentários. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#8-fa%C3%A7a-as-suas-altera%C3%A7%C3%B5es)
- [ ] O código segue as diretrizes de estilo e padrões de codificação do projeto.
- [ ] Todos os testes passam. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#testes)
- [ ] O Pull Request foi testado localmente. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#7-execute-o-brutils-localmente)
- [ ] Não há conflitos de mesclagem.

## Comentários Adicionais (opcional)

## Issue Relacionada

Closes #<numero_da_issue>

2024-09-13 20:05 UTC, antoniamaia requested changes
Oii @carlos-moreno, faltaram dois detalhes importantes: o item [10. Atualizar READMEs](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#10-atualizar-readmes) e o item [12. Adicione Entradas no CHANGELOG.md](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#12-adicione-entradas-no-changelogmd).. Muito obrigada pela contribuição!! 🎉

2024-09-15 16:06 UTC, carlos-moreno commented
Co-authored-by: Fernando Bezerra <fsbezerra@outlook.com>

2024-09-20 17:15 UTC, camilamaia commented on README.md
> +  * str or None: O código UF correspondente ao código IBGE, ou Nenhum se o
```suggestion
  * str or None: O código UF correspondente ao código IBGE, ou None se o
```

2024-09-20 17:17 UTC, camilamaia commented on tests/ibge/test_uf.py
> +        # implementar mais casos de teste aqui se necessário
```suggestion
```

2024-09-20 17:20 UTC, camilamaia reviewed
Boa, ficou lindão!! 👏  

Só comentei dois pequenos detalhes, mas fora isso já tá pronto para mergear. Se vcs quiserem, eu mesma posso atualizar aqui com as modificações e já dale.

2024-09-21 10:50 UTC, carlos-moreno commented
Boa, valeu pelas dicas @camilamaia 
Alterações indicadas feitas.

2024-09-23 13:51 UTC, camilamaia approved these changes

2024-09-23 14:14 UTC, antoniamaia approved these changes
Mandaram ver!! Obrigada pela contribuição e participação no tutorial, pessoal!! 🌟

2024-09-23 14:18 UTC, merged