Create Municipality Method
brazilian-utils/python pull request #412
Opened 2024-09-15 18:16 UTC by jaimenunes

## Descrição

Criação de uma nova funcionalidade para a obtenção de uma tupla contendo (município, UF) dado um código válido do IBGE.

## Mudanças Propostas

- Criação de funcionalidade 
## Checklist de Revisão

- [x] Eu li o [Contributing.md](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md)
- [x] Os testes foram adicionados ou atualizados para refletir as mudanças (se aplicável).
- [x] Foi adicionada uma entrada no changelog / Meu PR não necessita de uma nova entrada no changelog.
- [x] A [documentação](https://github.com/brazilian-utils/brutils-python/blob/main/README.md) em português foi atualizada ou criada, se necessário.
- [x] Se feita a documentação, a atualização do [arquivo em inglês](https://github.com/brazilian-utils/brutils-python/blob/main/README_EN.md). 
- [x] Eu documentei as minhas mudanças no código, adicionando docstrings e comentários. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#8-fa%C3%A7a-as-suas-altera%C3%A7%C3%B5es)
- [x] O código segue as diretrizes de estilo e padrões de codificação do projeto.
- [x] Todos os testes passam. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#testes)
- [x] O Pull Request foi testado localmente. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#7-execute-o-brutils-localmente)
- [ ] Não há conflitos de mesclagem.

## Comentários Adicionais (opcional)

## Issue Relacionada

Closes #<numero_da_issue>

2024-10-15 02:47 UTC, antoniamaia requested changes
@jaimenunes ficou incrível, muito obrigada pela contribuição! 🌟 Pelo que percebi está faltando apenas a entrada no [CHANGELOG.md](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#12-adicione-entradas-no-changelogmd), e alguns ajustes nos testes. Os avisos do codecov podem ajudar, nos avise se precisar de alguma ajuda!!

2024-10-16 19:43 UTC, antoniamaia commented on CHANGELOG.md
> +- Utilitário `get_municipality_by_code` [412](https://github.com/brazilian-utils/brutils-python/pull/412)
```suggestion

```

2024-10-16 21:52 UTC, antoniamaia requested changes
Boa, @jaimenunes um PR de rexxxpeito!! 🚀  Ficou mesmo só aquele detalhe no arquivo `CHANGELOG.md` que não consegui ajustar por aqui, senão já era merge certeiro! Obrigada pela contribuição!! 🥇

2024-10-17 23:37 UTC, jaimenunes commented on CHANGELOG.md
> +- Utilitário `get_municipality_by_code` [412](https://github.com/brazilian-utils/brutils-python/pull/412)
@antoniamaia , aaah tinha colocado no lugar errado mesmo. Alterei aqui, agora acredito que esteja correto. 😄

2024-11-18 21:00 UTC, camilamaia commented on README_EN.md
> +```python
Só adicionando um espacinho que tava faltando:
```suggestion

```python
```

2024-11-18 21:00 UTC, camilamaia commented on README.md
> +```python
Só adicionando um espacinho que tava faltando:

```suggestion

```python
```

2024-11-18 21:01 UTC, camilamaia approved these changes
Booooa @jaimenunes! Eu só fiz duas minis sugestões que já vou comitar e mergear mesmo. Valeu pela contribuição!!

2024-11-18 21:05 UTC, merged