Adicionando utilitário convert_uf_to_text
brazilian-utils/python pull request #421
Opened 2024-10-06 13:13 UTC by low-ise

## Descrição

## Mudanças Propostas

## Checklist de Revisão

- [ ] Eu li o [Contributing.md](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md)
- [ ] Os testes foram adicionados ou atualizados para refletir as mudanças (se aplicável).
- [ ] Foi adicionada uma entrada no changelog / Meu PR não necessita de uma nova entrada no changelog.
- [ ] A [documentação](https://github.com/brazilian-utils/brutils-python/blob/main/README.md) em português foi atualizada ou criada, se necessário.
- [ ] Se feita a documentação, a atualização do [arquivo em inglês](https://github.com/brazilian-utils/brutils-python/blob/main/README_EN.md). 
- [ ] Eu documentei as minhas mudanças no código, adicionando docstrings e comentários. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#8-fa%C3%A7a-as-suas-altera%C3%A7%C3%B5es)
- [ ] O código segue as diretrizes de estilo e padrões de codificação do projeto.
- [ ] Todos os testes passam. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#testes)
- [ ] O Pull Request foi testado localmente. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#7-execute-o-brutils-localmente)
- [ ] Não há conflitos de mesclagem.

## Comentários Adicionais (opcional)

## Issue Relacionada

Closes #<numero_da_issue>

2024-10-15 03:24 UTC, antoniamaia commented on tests/ibge/test_uf.py
> +        # Testes com espaços em branco
```suggestion

```

2024-10-15 03:31 UTC, antoniamaia requested changes
Boa, meninas!! @low-ise faltaram apenas alguns detalhes: Adicionar a entrada no [CHANGELOG.md](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#12-adicione-entradas-no-changelogmd), atualizar a [documentação nos READMES](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#10-atualizar-readmes) PT e EN.
Muito obrigada pela contribuição!! ficamos muito felizes em ver o PR de vocês por aqui <3 Se precisarem de algo, só chamar!!

2024-12-19 18:46 UTC, camilamaia commented on tests/ibge/test_uf.py
> +  convert_uf_to_text,
Arrumando erro de lint, erro de indentação:

```suggestion
    convert_code_to_uf, 
    convert_uf_to_text,
```

2024-12-19 18:48 UTC, camilamaia commented on tests/ibge/test_uf.py
> +    convert_code_to_uf,
Espaço extra está causando erro de lint:

```suggestion
    convert_code_to_uf,
```

2024-12-19 18:51 UTC, camilamaia commented
Oii @low-ise! Eu atualizei o PR e resolvi os conflitos. Agora só falta realmente fazer as mudanças que a @antoniamaia apontou. Qualquer coisa só dar um grito!

2025-01-13 13:27 UTC, camilamaia commented on brutils/__init__.py
> +
```suggestion
```

2025-05-13 17:04 UTC, camilamaia commented
Oi, @low-ise ! Estou fechando o PR por inatividade, mas fique à vontade para reabrir caso queira retomar o trabalho. 😊

2025-05-13 17:04 UTC, closed without merging