Adiciona utilitário de formatação monetária
brazilian-utils/python pull request #434
Opened 2024-10-21 18:41 UTC by morais90

## Descrição
Adiciona uma nova função para formatar números no formato monetário brasileiro.

## Mudanças Propostas
Esse PR propõe a adição do método `format_currency` para formatar números seguindo o formato monetário brasileiro. A função recebe como input um número float ou Decimal e realiza a formatação seguindo o padrão: `R$ XX.XX,XX`, onde os agrupadores de milhar serão separados mediante ponto e a casa decimal por meio de vírgula.

Como ponto importante, foi avaliado uma solução através do módulo `locale`, porém dado a necessidade da existência dos pacotes `locales` no sistema operacional, a proposta foi feita de forma manual e sem acoplamento de pacotes externos.

Exemplo de uso:
```python
>>> from brutils.currency import format_currency
>>> format_currency(1259.03)
'R$ 1.259,03'
>>> format_currency(0)
'R$ 0,00'
>>> format_currency("not a number")
None
```

## Checklist de Revisão

- [x] Eu li o [Contributing.md](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md)
- [x] Os testes foram adicionados ou atualizados para refletir as mudanças (se aplicável).
- [ ] Foi adicionada uma entrada no changelog / Meu PR não necessita de uma nova entrada no changelog.
- [x] A [documentação](https://github.com/brazilian-utils/brutils-python/blob/main/README.md) em português foi atualizada ou criada, se necessário.
- [x] Se feita a documentação, a atualização do [arquivo em inglês](https://github.com/brazilian-utils/brutils-python/blob/main/README_EN.md). 
- [ ] Eu documentei as minhas mudanças no código, adicionando docstrings e comentários. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#8-fa%C3%A7a-as-suas-altera%C3%A7%C3%B5es)
- [x] O código segue as diretrizes de estilo e padrões de codificação do projeto.
- [x] Todos os testes passam. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#testes)
- [x] O Pull Request foi testado localmente. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#7-execute-o-brutils-localmente)
- [] Não há conflitos de mesclagem.

## Comentários Adicionais (opcional)

## Issue Relacionada

Closes #<numero_da_issue>

2024-12-19 19:09 UTC, camilamaia requested changes
@morais90 Olha eu aqui revisando hah Antes tarde do que mais tarde 😆 

PR tá show. Já arrumei os conflitos. Agora só falta adicionar a entrada no [CHANGELOG.md](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#12-adicione-entradas-no-changelogmd). Assim que vc adicionar já dou o approve e merge aqui :)

2024-12-24 20:46 UTC, morais90 commented
> @morais90 Olha eu aqui revisando hah Antes tarde do que mais tarde 😆
> 
> PR tá show. Já arrumei os conflitos. Agora só falta adicionar a entrada no [CHANGELOG.md](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#12-adicione-entradas-no-changelogmd). Assim que vc adicionar já dou o approve e merge aqui :)

Que isso haha, não tem pressa não 😄 . Ajustei o CHANGELOG com a entrada da issue 🚀

2025-01-13 12:09 UTC, camilamaia commented on CHANGELOG.md
> +- Utilitário `get_code_by_municipality_name` [#399](https://github.com/brazilian-utils/brutils-python/issues/399)
```suggestion
```

2025-01-13 12:09 UTC, camilamaia approved these changes
Dale!!!!

2025-01-13 12:12 UTC, merged