437
brazilian-utils/python pull request #444
Opened 2024-10-24 20:20 UTC by vmagueta

## Descrição
Implementada a função `remove_symbols_cpf`, que irá remover os símbolos `.` e `-` do CPF fornecido. Em caso de envio de string vazia, ou um inteiro, ou um CPF faltando números ou com números a mais, irá retornar None. Também implementada a Docstring e a doctest, conforme solicitado na issue #437. Adicionado os testes unitários referente a essa função, testando positivamente para remover os symbols, negativo para cpf inválidos ou não formatados.

## Checklist de Revisão

- [ ] Eu li o [Contributing.md](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md)
- [ ] Os testes foram adicionados ou atualizados para refletir as mudanças (se aplicável).
- [ ] Foi adicionada uma entrada no changelog / Meu PR não necessita de uma nova entrada no changelog.
- [ ] A [documentação](https://github.com/brazilian-utils/brutils-python/blob/main/README.md) em português foi atualizada ou criada, se necessário.
- [ ] Se feita a documentação, a atualização do [arquivo em inglês](https://github.com/brazilian-utils/brutils-python/blob/main/README_EN.md). 
- [ ] Eu documentei as minhas mudanças no código, adicionando docstrings e comentários. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#8-fa%C3%A7a-as-suas-altera%C3%A7%C3%B5es)
- [ ] O código segue as diretrizes de estilo e padrões de codificação do projeto.
- [ ] Todos os testes passam. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#testes)
- [ ] O Pull Request foi testado localmente. [Instruções](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#7-execute-o-brutils-localmente)
- [ ] Não há conflitos de mesclagem.

## Issue Relacionada

Closes #437

2024-10-25 01:56 UTC, fabiogjo requested changes

2024-10-25 01:56 UTC, fabiogjo commented on brutils/cpf.py
> +            return cpf_no_symbols
```suggestion
    result = None
    if not isinstance(cpf, str) or cpf == "":
        cpf_no_symbols = ''.join([char for char in cpf if char not in ".-"])
        
        if len(cpf_no_symbols) == 11:
            result = cpf_no_symbols 
            
     return result
```

2024-10-25 01:56 UTC, fabiogjo commented on brutils/cpf.py
> +            return cpf_no_symbols
Creio q dessa maneira fica mais legivel o codigo, verificamos o tipo do cpf apenas em 1 if, utilizamos um list-comprehension para lidar com o tratamento da string que fica mais enxuto e mais legivel tambem, e deixamos apenas um retorno na função, oq é o ideal.

2024-10-25 14:29 UTC, vmagueta commented on brutils/cpf.py
> +            return cpf_no_symbols
Obrigado pelo retorno, fabio. Já alterei conforme solicitado. Realmente ficou muito melhor mesmo. Muito obrigado!

2024-10-25 21:36 UTC, fabiogjo commented on brutils/cpf.py
> +    cpf_no_symbols = ""
pode remover essa linha aqui, nao esta fazendo mais nada.

2024-10-25 21:36 UTC, fabiogjo approved these changes

2024-10-25 22:15 UTC, vmagueta commented on brutils/cpf.py
> +    cpf_no_symbols = ""
Fabio, qual linha? Desculpe, sou iniciante ainda.

2024-10-27 17:31 UTC, FabioCruzDev commented on brutils/cpf.py
> +    cpf_no_symbols = ""
@vmagueta claro sem problemas mano, pode remover a linha 276 onde esta sendo declarada a variavel cpf_no_symbols, não precisamos fazer essa atribuição aqui pois estamos declarando ela com o valor na linha 278.

2024-10-28 12:30 UTC, niltonpimentel02 commented
@vmagueta fala meu nobre! uma dica, sempre coloque um título descritivo no teu pr pra aumentar as chances de revisão como "adiciona função para remover símbolos específicos de cpf" ou algo que deixe claro sobre o que é esse novo código.

o @FabioCruzDev já deu umas dicas boas pra melhorar o código mas ainda podemos melhorar um pouquinho mais.. se quiser podemos marcar uma call rapidinha e fazemos juntos.. te mandei uma mensagem no linkedin 😄

2024-10-28 13:13 UTC, vmagueta commented
> @vmagueta fala meu nobre! uma dica, sempre coloque um título descritivo no teu pr pra aumentar as chances de revisão como "adiciona função para remover símbolos específicos de cpf" ou algo que deixe claro sobre o que é esse novo código.
> 
> o @FabioCruzDev já deu umas dicas boas pra melhorar o código mas ainda podemos melhorar um pouquinho mais.. se quiser podemos marcar uma call rapidinha e fazemos juntos.. te mandei uma mensagem no linkedin 😄

Poxa, com certeza @niltonpimentel02 , vai ser muito bom ter esta tua ajuda em call, se não for te atrapalhar! Inclusive, já te respondi no Linkedin. Muitíssimo obrigado!

2025-01-13 13:19 UTC, camilamaia commented
@vmagueta valeu pela contribuição! Como mencionei na própria issue #437 , eu acredito que esse utilitário já está implementado: https://github.com/brazilian-utils/brutils-python?tab=readme-ov-file#remove_symbols_cpf
Essa função já faz exatamente o quê a issue está pedindo.

Por isso, vou fechar esse PR por enquanto, beleza? Caso a gente perceba que na verdade a issue não está duplicada, aí eu reabro, beleza?

Valeu!

2025-01-13 13:19 UTC, closed without merging